version: "3.9"

services:
  ntop_blocker:
    build: .
    container_name: ntop_blocker
    restart: unless-stopped
    ports:
      - "5000:5000"
    env_file:
      - .env
    volumes:
      - ./scripts:/app/scripts
    cap_add:
      - NET_ADMIN
